constant_exposure:
  path: /js/constant-exposure.{_format}
  controller: ConstantExposureBundle\Controller\ExposeController::index
  defaults:
    _format: 'json'
  requirements:
    _format: '[a-z0-9]{2,}'
