on: [pull_request]
name: Tests

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v1
      - uses: chindit/actions-phpunit-symfony@1.0.0
