on: [pull_request]
name: Tests

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-php@master
        with:
          php-version: '7.2'
      - run: composer install
      - run: php vendor/bin/simple-phpunit
